# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-20 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0002_auto_20200520_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0319750b-4bf9-43e5-84d3-f69fcb0099f1'), primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
    ]
