# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curiosity', '0003_auto_20200520_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.RemoveField(
            model_name='image',
            name='urls_x300',
        ),
        migrations.RemoveField(
            model_name='image',
            name='urls_x600',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fimg',
        ),
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Альтернативный текст'),
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.TextField(default=None, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='Интификатор'),
        ),
        migrations.AlterField(
            model_name='image',
            name='role',
            field=models.CharField(blank=True, choices=[('о', 'Обложка'), ('б1', 'Блок 1'), ('б2', 'Блок 2'), ('б3', 'Блок 3'), ('б4', 'Блок 4'), ('б5', 'Блок 5'), ('б6', 'Блок 6'), ('б8', 'Блок 8'), ('б9', 'Блок 9'), ('б10', 'Блок 10')], default='о', max_length=2, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curiosity.PostAuthor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
