# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-18 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='ip',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
