# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-18 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_pageview_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(max_length=50, verbose_name='Subtitle')),
                ('link_text', models.CharField(max_length=50, verbose_name='Link text')),
                ('link_url', models.CharField(max_length=50, verbose_name='Link url')),
            ],
        ),
    ]
