# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_auto_20200518_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomepage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
    ]
