# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_welcomepage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomepageblock',
            name='link_text',
            field=models.CharField(max_length=250, verbose_name='Link text'),
        ),
        migrations.AlterField(
            model_name='welcomepageblock',
            name='link_url',
            field=models.CharField(max_length=250, verbose_name='Link url'),
        ),
        migrations.AlterField(
            model_name='welcomepageblock',
            name='subtitle',
            field=models.CharField(max_length=250, verbose_name='Subtitle'),
        ),
    ]
